services:
  frontend:
    image: hecf-frontend:latest
    container_name: hecf-frontend
    ports:
      - "${FRONTEND_PORT:-5173}:80"
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL:-http://localhost:8080/api}
    depends_on:
      - backend

  backend:
    image: hecf-backend:latest
    container_name: hecf-backend
    volumes:
      - ./02_Backend/output:/app/output
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI:-mongodb://mongo:27017/Listings}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}

  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
