services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: matickuhar/hecf-backend:latest
    container_name: hecf-backend
    volumes:
      - ./output:/app/output
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://testUser:testUserPassword@mongo:27017/hecf?authSource=admin
      - OPENAI_API_KEY=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
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    #ports:
    #  - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testUser
      - MONGO_INITDB_ROOT_PASSWORD=testUserPassword

volumes:
  mongo_data: